events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    
    server {
        listen 8082;
        server_name localhost;
        
        location / {
            add_header Content-Type application/json;
            return 200 '{"service": "order-service", "message": "API de Pedidos funcionando!", "endpoint": "/", "status": "ok"}';
        }
        
        location /orders {
            add_header Content-Type application/json;
            return 200 '{"service": "order-service", "message": "Lista de pedidos", "orders": [{"id": 1, "userId": 1, "total": 2550.00, "status": "completed"}, {"id": 2, "userId": 2, "total": 100.00, "status": "pending"}], "status": "ok"}';
        }
        
        location /orders/1 {
            add_header Content-Type application/json;
            return 200 '{"service": "order-service", "message": "Pedido encontrado", "order": {"id": 1, "userId": 1, "total": 2550.00, "status": "completed", "items": ["Notebook", "Mouse"]}, "status": "ok"}';
        }
    }
}

