events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    
    server {
        listen 8080;
        server_name localhost;
        
        location / {
            add_header Content-Type application/json;
            return 200 '{"service": "user-service", "message": "API de Usuários funcionando!", "endpoint": "/", "status": "ok"}';
        }
        
        location /users {
            add_header Content-Type application/json;
            return 200 '{"service": "user-service", "message": "Lista de usuários", "users": [{"id": 1, "name": "João"}, {"id": 2, "name": "Maria"}], "status": "ok"}';
        }
        
        location /users/1 {
            add_header Content-Type application/json;
            return 200 '{"service": "user-service", "message": "Usuário encontrado", "user": {"id": 1, "name": "João", "email": "joao@email.com"}, "status": "ok"}';
        }
    }
}

