gateway:
  services:
    USER_SERVICE:
      url: http://user-service:8080
    PRODUCT_SERVICE:
      url: http://product-service:8081
    ORDER_SERVICE:
      url: http://order-service:8082

logging:
  level:
    com.example.gateway: INFO
    org.springframework.cloud.gateway: INFO
