version: "3.3"

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "temp"
      POSTGRES_USER: "jeanfernandes"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - "/var/lib/postgresql/data/"
    container_name: pg_qualquer

